// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnolo-09fEKfR7Nc0nnjPMxBOIHjQK6sg',
    appId: '1:886864504275:web:d8246f38025b743f78bb26',
    messagingSenderId: '886864504275',
    projectId: 'afterschool-c2b8e',
    authDomain: 'afterschool-c2b8e.firebaseapp.com',
    storageBucket: 'afterschool-c2b8e.appspot.com',
    measurementId: 'G-PLSWJMTLCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQjXaNWdW_uqMztb4Cff5GlywE36qdigk',
    appId: '1:886864504275:android:a692d2a7e96c002078bb26',
    messagingSenderId: '886864504275',
    projectId: 'afterschool-c2b8e',
    storageBucket: 'afterschool-c2b8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSYw2va-76XEqe8aeaKPhdmhLeHYiebxU',
    appId: '1:886864504275:ios:26858248accd639f78bb26',
    messagingSenderId: '886864504275',
    projectId: 'afterschool-c2b8e',
    storageBucket: 'afterschool-c2b8e.appspot.com',
    androidClientId: '886864504275-qk5boff3fk5soquh4q47ktnput3kflkl.apps.googleusercontent.com',
    iosClientId: '886864504275-aoqi7inqefoji0071knra88ikifm9ua0.apps.googleusercontent.com',
    iosBundleId: 'com.example.afterschool',
  );
}
